import {
  Component,
  input,
  LOCALE_ID,
  computed,
  signal,
  SecurityContext,
  inject,
  ChangeDetectionStrategy,
} from '@angular/core';
import { DomSanitizer, SafeResourceUrl } from '@angular/platform-browser';
import {
  ASYNC_INTERNAL_MATOMO_CONFIGURATION,
  getTrackersConfiguration,
  InternalMatomoConfiguration,
  isAutoConfigurationMode,
  isExplicitTrackerConfiguration,
} from '../tracker/configuration';
import { coerceCssSizeBinding, CssSizeInput } from '../utils/coercion';

const DEFAULT_BORDER = '0';
const DEFAULT_WIDTH = '600px';
const DEFAULT_HEIGHT = '200px';
const URL_PATTERN =
  '{SERVER}/index.php?module=CoreAdminHome&action=optOut&language={LOCALE}&backgroundColor={BG_COLOR}&fontColor={COLOR}&fontSize={FONT_SIZE}&fontFamily={FONT_FAMILY}';

function missingServerUrlError(): Error {
  return new Error(
    `It is required to set [serverUrl] when Matomo configuration mode is set to 'manual'`,
  );
}

/**
 * Basic opt-out form, based on an iframe auto-generated by Matomo.
 *
 * <b>WARNING:</b> By default, this component assumes the tracker url set in MatomoConfiguration is
 * safe to be used as an iframe `src`. You have to make sure that this url is safe before using this
 * component!
 *
 * Note: This component relies on the matomo-generated opt-out form, which is deprecated
 * since Matomo version 4.12.0. It will be marked as deprecated soon.
 *
 * @see https://developer.matomo.org/changelog#new-privacy-opt-out-options
 */
@Component({
  selector: 'matomo-opt-out-form',
  templateUrl: './matomo-opt-out-form.component.html',
  changeDetection: ChangeDetectionStrategy.Eager,
})
export class MatomoOptOutFormComponent {
  private readonly sanitizer = inject(DomSanitizer);
  private readonly config = inject<Promise<InternalMatomoConfiguration>>(
    ASYNC_INTERNAL_MATOMO_CONFIGURATION,
  );

  private readonly defaultServerUrl = signal<string | undefined>(undefined);
  private readonly configInitialized = signal(false);
  readonly border = input(DEFAULT_BORDER, { transform: coerceCssSizeBinding });
  readonly width = input(DEFAULT_WIDTH, { transform: coerceCssSizeBinding });
  readonly height = input(DEFAULT_HEIGHT, { transform: coerceCssSizeBinding });
  /**
   * Set a custom locale for the opt-out form
   * <br>
   * Default is the current app locale available in LOCALE_ID token
   */
  readonly locale = input<string>(inject(LOCALE_ID, { optional: true }) ?? '');
  /** Font color (note that Matomo currently only supports hexadecimal without leading hash notation) */
  readonly color = input<string>('');
  /** Background color (note that Matomo currently only supports hexadecimal without leading hash notation) */
  readonly backgroundColor = input<string>('');
  readonly fontSize = input<string>('');
  readonly fontFamily = input<string>('');
  /**
   * Set a custom Matomo server url to be used for iframe generation
   * <br>
   * By default, tracker url is retrieved from MatomoConfiguration.
   * <br>
   * <b>WARNING:</b> This component assumes the url you provide is safe to be used as an iframe
   * `src`. You have to make sure that this url is safe before using this component!
   */
  readonly serverUrl = input<SafeResourceUrl | undefined>(undefined);

  readonly iframeSrc = computed<SafeResourceUrl>(() => {
    const serverUrlOverride = this.serverUrl();
    const defaultServerUrl = this.defaultServerUrl();
    const initialized = this.configInitialized();

    let serverUrl: string | null | undefined;

    if (serverUrlOverride) {
      serverUrl = this.sanitizer.sanitize(SecurityContext.RESOURCE_URL, serverUrlOverride);
    } else {
      serverUrl = defaultServerUrl;
    }

    if (!serverUrl) {
      if (initialized) {
        throw missingServerUrlError();
      }
      return this.sanitizer.bypassSecurityTrustResourceUrl('');
    }

    const url = URL_PATTERN.replace('{SERVER}', serverUrl)
      .replace('{LOCALE}', encodeURIComponent(this.locale()))
      .replace('{COLOR}', encodeURIComponent(this.color()))
      .replace('{BG_COLOR}', encodeURIComponent(this.backgroundColor()))
      .replace('{FONT_SIZE}', encodeURIComponent(this.fontSize()))
      .replace('{FONT_FAMILY}', encodeURIComponent(this.fontFamily()));

    return this.sanitizer.bypassSecurityTrustResourceUrl(url);
  });

  constructor() {
    this.config.then(config => {
      if (isAutoConfigurationMode(config) && isExplicitTrackerConfiguration(config)) {
        this.defaultServerUrl.set(getTrackersConfiguration(config)[0].trackerUrl);
      }
      this.configInitialized.set(true);
    });
  }

  static ngAcceptInputType_border: CssSizeInput;
  static ngAcceptInputType_width: CssSizeInput;
  static ngAcceptInputType_height: CssSizeInput;
}
